### ISSUE TITLE
installed on mac Error

### ISSUE THREAD

**Issue by binnz** [dgraph-io/Install-Dgraph#22]
installed on mac by `curl https://get.dgraph.io -sSf | bash`

```
Do you agree to the terms of the Dgraph Community License? [Y/n] y
Latest release version is v21.03.0.
Downloading checksum file for v21.03.0 build.
######################################################################## 100.0%
Download complete.
There was some problem while installing Dgraph. Please share the output of this script with us on https://discuss.dgraph.io so that we can resolve the issue for you.
```

**Comment by nervouscat** [comment]
Same issue happening on my end too, it seems the latest version is not working with Mac OS, i tried setting it to version before:

` curl -sSf https://get.dgraph.io | VERSION=v20.11.3   bash
` 
and it seemed to work.

**Comment by binnz** [comment]
> Same issue happening on my end too, it seems the latest version is not working with Mac OS, i tried setting it to version before:
> 
> `curl -sSf https://get.dgraph.io | VERSION=v20.11.3 bash`
> and it seemed to work.

It works for me, thanks.
